### ISSUE TITLE
Verduidelijk welke Zakaria je bent

### ISSUE THREAD

**Issue by ophalvens** [Zakaria1601/MI1#1]
@Zakaria1601 kan je in je repository aub aangeven welke Zakaria je juist bent? Er zitten alleen al in jouw klasgroep 3 Zakaria's. 

Je interview moet je ook nog in html formaat toevoegen aan je repository.

**Comment by Zakaria1601** [comment]
Ik ben Zakaria Ajbar

**Comment by ophalvens** [comment]
Bedankt, Zakaria!
